name: $(Build.BuildId).$(Year:yy)$(DayOfYear)

trigger:
- master
- develop
- dev

resources:
  repositories:
    - repository: templates
      type: git
      name: Audacia/Audacia.Build.Templates
      
steps:
- template: build-signed-package.netcore.yaml@templates